### ISSUE TITLE
How to enable and start a service / timer?

### ISSUE THREAD

**Issue by jkirk** [shibumi/ansible-systemd-conf#1]
It seems like there is no way to enable and/or start defined service / timer with this role, right?

Currently I do something like this:
```
  roles:
    - role: systemd-conf
      systemd_conf_timer:
        restic-backup-prune:
          - Unit:
            - Description: "Weekly restic backup prune"
          - Timer:
            - OnCalendar: "Sun *-*-* 12:00"
            - Persistent: "True"
          - Install:
            - WantedBy: "timers.target"
      systemd_conf_service:
        restic-backup-prune:
          - Unit:
            - Description: "Weekly restic backup prune"
          - Service:
            - Type: "oneshot"
            - ExecStart: "/usr/local/bin/restic --password-file /root/.restic_data_password -r /srv/backups/restic/backup01 forget --keep-daily 30 --keep-weekly 8 --keep-monthly 12 --keep-yearly 75 --keep-last 60 --prune"
  tasks:
    - name: "Enable and start timers/services"
      service:
        name:  restic-backup-prune.timer
        state: started
        enabled: true
```

Is there a better way to this?
